platform :ios, '11.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  # Automatic Capacitor Pod dependencies, do not delete
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCommunityTwitter', :path => '../../node_modules/@capacitor-community/twitter'
  pod 'CapacitorPluginFfmpeg', :path => '../../../capacitor-plugin-ffmpeg'
  # Do not delete
end

target 'App' do
  capacitor_pods
  # Add your Pods here
  pod 'mobile-ffmpeg-full', '~> 4.4'
end
